# Generated by Django 5.2.1 on 2025-05-24 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAdministrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('001', 'Banco do Brasil')], max_length=255)),
                ('agency', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('current', 'Current'), ('saving', 'Saving')], max_length=20)),
                ('pix_key', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.company')),
            ],
        ),
        migrations.CreateModel(
            name='CouponReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/coupons')),
                ('date', models.DateTimeField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.company')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='marketplace.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Stored in cents. For example: 199 = R$1.99')),
                ('file', models.FileField(upload_to='receipts/payment')),
                ('paid_at', models.DateTimeField()),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.generaladministrator')),
                ('coupon_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.couponreceipt')),
            ],
        ),
    ]
