# Generated by Django 5.2.1 on 2025-07-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.product'),
        ),
    ]
